### ISSUE TITLE
Incompatible with BTTV

### ISSUE THREAD

**Issue by kanegasi** [jpgohlke/twitch-chat-filter#105]
There is a browser addon called "BetterTTV" created and maintained by NightDev, the creators of NightBot. This script is incompatible with the addon and causes the filter to not work (nothing in chat gets filtered). There's also some funkyness with the setting buttons on the bottom.

BetterTTV: http://www.nightdev.com/betterttv/

**Comment by Freso** [comment]
I would like to see this happen.

**Comment by Tyrrr** [comment]
I'd also love to have both scripts at the same time. What's weird is that the all lowercase function works but the filters don't.

**Comment by hugomg** [comment]
The lowercase functions working is just a coincidence. All we are doing is adding some css to the chat window that makes all the text inside it display as lowercase. If you inspect the raw HTML via the developer tools you will see that the real text still contains upper case letters and its just being displayed differently. This is also why turning the lowercase filter on and off works.

Its been a while since I checked this but IIRC the big problem is that TCF works by mucking with the internals of the official twitch chat system and bttv reimplements those internals in an incompatible manner.
